---
title: "M5_W2_Reproducible_Research_Markdown_and_knitr"
author: "Alexander Cormack"
date: "2023-02-27"
output:
  html_document: default
  word_document: default
---

# Markdown and knitr

## Coding Standards for R

1. Always use text files / text editor
2. Indent your code
    - indenting improves readability
    - suggested: indents of 4 spaces at a minimum; 8 spaces ideal
3. Limit the width of your code (80 columns?)
    - fixing line length prevents lots of nesting and very long functions
4. Limit the length of individual functions
    - limit it to one basic activity, i.e. only read data or process data, or fit a model or print some output
    - helps with debugging

## Introduction to Markdown

### What is markdown?

*Markdown is a text-to-HTML conversion tool for web writers. Markdown allows you to write using an easy-to-read, easy-to-write plain text format, then convert it to structurally valid XHTML (or HTML).*

John Gruber, creator of markdown

### Markdown syntax

- Italics: wrap text in single asterisks or underscores
- Bold: wrap text in double asterisks or underscores
- Italics and bold: wrap text in triple asterisks or asterisks and underscores
- Strikethrough: wrap text in double tildes
- Headings: use hashtags to create 1st, 2nd ... 6th level headings
- Bulleted lists: use a dash (or any other character consistently across the list) and a space at the beginning of the line
- Numbered lists: use a number, a full stop and a space
- Indents: at least one leading space at the beginning of a line - introduces a blank line above and an indent by the number of spaces
- Links: enclose the link text in square brackets followed by the link address in round brackets
- Advanced linking: enclose the link text in square brackets immediately followed by a number in square brackets. Later on in the document list all the links with the number in square brackets followed by a colon followed by the link address followed by the link text in quotation marks
- Newlines: requires a double space at the end of a line
- See the Github cheatsheet for the following formatting tips:
    - images
    - code and syntax highlighting
    - footnotes
    - tables
    - blockquotes
    - inline HTML
    - horizontal rule

[The Official Markdown Documentation][1]  
[Github's Markdown Cheatsheet][2]

[1]: https://www.markdownguide.org "The Official Markdown Documentation"
[2]: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet "Github's Markdown Cheatsheet"

## R Markdown

### What is markdown?

- Created by [John Gruber](https://daringfireball.net) and Aaron Schwartz
- A simplified version of "markup" languages
- Allows one to focus on writing as opposed to formatting
- Simple/minimal intuitive formatting elements
- Easily converted to valid HTML (and other formats) using existing tools
- Complete information is available at http://daringfireball.net/projects/markdown/
- Some background information at http://daringfireball.net/2004/03/dive_into_markdown

### What is R markdown?

- R markdown is the integration of R code with markdown
- Allows one to create documents containing "live" R code
- R code is evaluated as part of the processing of the markdown
- Results from R code are inserted into markdown document
- A core tool in **literate statistical programming**

- R markdown can be converted to standard markdown using the knitr package in R
- Markdown can be converted to HTML using the markdown package in R
- Any basic text editor can be used to create a markdown document; no special editing tools needed
- The R markdown --> markdown --> HTML work flow can be easily managed using RStudio (but not required)

## knitr (Part 1)

### Problems, problems

- Authors must undertake considerable effort to put data/results on the web
- Readers must download data/results individually and piece together which data go with which code sections, etc.
- Authors/readers must manually interact with websites
- There is no single document to integrate data analysis with textual representations; i.e. data, code, and text are not linked









